// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function LoadPDFEditorSettings(): $CancellablePromise<string> {
    return $Call.ByID(4103014046);
}

export function SavePDFEditorSettings(data: string): $CancellablePromise<string> {
    return $Call.ByID(4070856781, data);
}
