// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class JSONItem {
    "filename": string;
    "content": string;

    /** Creates a new JSONItem instance. */
    constructor($$source: Partial<JSONItem> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JSONItem instance from a string or object.
     */
    static createFrom($$source: any = {}): JSONItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JSONItem($$parsedSource as Partial<JSONItem>);
    }
}
