// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportFile(path: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2785325084, path, data);
}

export function ListWorkouts(): $CancellablePromise<$models.JSONItem[]> {
    return $Call.ByID(538148056).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadWorkout(name: string): $CancellablePromise<string> {
    return $Call.ByID(4197301079, name);
}

export function SaveWorkout(data: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3461505736, data, name);
}

// Private type creation functions
const $$createType0 = $models.JSONItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
